// ─────────────────────────────────────────────────────────────────────────────
// Feral CCF — CF/x3 Act NodeCode: invoke a tool on a federated CF/x3 source.
// Catalog nodes (one per manifest tool) are generated by Cfx3CatalogSource.
// ─────────────────────────────────────────────────────────────────────────────

import type { Context } from '../../context/context.js';
import type { Result } from '../../result/result.js';
import { ResultStatus } from '../../result/result.js';
import type { ConfigurationDescription, ResultDescription } from '../../configuration/configuration-description.js';
import { AbstractNodeCode } from '../abstract-node-code.js';
import { NodeCodeCategory } from '../node-code.js';
import { actOnSourceById } from '../../../cfx3/service.js';

export class Cfx3ActNodeCode extends AbstractNodeCode {
    readonly allowExtraConfig = true;

    static readonly configDescriptions: ConfigurationDescription[] = [
        { key: 'source_id', name: 'Source ID', description: 'The CF/x3 source to act on.', type: 'string' },
        { key: 'tool', name: 'Tool', description: 'Tool id to invoke (from the source manifest).', type: 'string' },
        { key: 'args_context_path', name: 'Args Path', description: 'Context key holding the tool args object.', type: 'string', default: 'cfx3_args' },
        { key: 'result_context_path', name: 'Result Path', description: 'Context key to store the tool result.', type: 'string', default: 'cfx3_result' },
    ];
    static readonly resultDescriptions: ResultDescription[] = [
        { status: ResultStatus.OK, description: 'Tool executed successfully.' },
        { status: ResultStatus.ERROR, description: 'Tool failed or returned not-ok.' },
    ];

    constructor() {
        super('cfx3_act', 'CF/x3 Act', 'Invoke a tool on a federated CF/x3 source.', NodeCodeCategory.DATA);
    }

    async process(context: Context): Promise<Result> {
        const sourceId = this.getRequiredConfigValue('source_id') as string;
        const tool = this.getRequiredConfigValue('tool') as string;
        const argsPath = this.getRequiredConfigValue('args_context_path', 'cfx3_args') as string;
        const resultPath = this.getRequiredConfigValue('result_context_path', 'cfx3_result') as string;

        let args: Record<string, unknown> = {};
        if (context.has(argsPath)) {
            const raw = context.get(argsPath);
            if (raw && typeof raw === 'object') args = raw as Record<string, unknown>;
        }

        try {
            const res = await actOnSourceById(sourceId, tool, args);
            context.set(resultPath, res);
            return res.ok
                ? this.result(ResultStatus.OK, `CF/x3 ${sourceId} ${tool} ok.`)
                : this.result(ResultStatus.ERROR, `CF/x3 ${sourceId} ${tool}: ${res.message ?? 'not ok'}`);
        } catch (err) {
            return this.result(ResultStatus.ERROR, `CF/x3 act failed: ${err instanceof Error ? err.message : String(err)}`);
        }
    }
}
