// ─────────────────────────────────────────────────────────────────────────────
// Category Processes — Pre-built Feral processes for classified request types
//
// These are data-gathering pipelines: they collect relevant context from CxMS
// and let feralChatHeadless's synthesizeResponse() turn results into a reply.
//
// Categories covered here (deterministic, efficient):
//   query         → search entities → synthesize
//   analytical    → list types + search → synthesize with analysis
//   introspection → list types + search → synthesize with capability overview
//
// Categories NOT covered (handled by the existing LLM-driven pipeline):
//   task, remember, create  — arbitrary entity operations; dynamic processes
//                             generated by the reason model are better suited
//   chat    — bypassed entirely in feralChatHeadless before process dispatch
//   none    — falls through to existing pipeline
// ─────────────────────────────────────────────────────────────────────────────

import { hydrateProcess } from '../process/process-json-hydrator.js';
import type { Process } from '../process/process.js';
import type { RequestCategory } from '../../context/request-classifier.js';

// ── query ────────────────────────────────────────────────────────────────────
// Searches CxMS for entities matching the user's question.
// search_entities auto-falls back to user_input when no query is set.

const queryProcess: Process = hydrateProcess({
    schema_version: 1,
    key: 'phaibel.query',
    description: 'Retrieve stored information to answer user questions about tasks, events, notes, goals, people, or any other tracked data',
    context: {},
    nodes: [
        {
            key: 'start',
            catalog_node_key: 'start',
            configuration: {},
            edges: { ok: 'search' },
        },
        {
            key: 'search',
            description: 'Search for entities matching the question',
            catalog_node_key: 'search_entities',
            configuration: { context_path: 'search_results' },
            edges: { ok: 'done', not_found: 'done', error: 'done' },
        },
        {
            key: 'done',
            catalog_node_key: 'stop',
            configuration: {},
            edges: {},
        },
    ],
});

// ── analytical ───────────────────────────────────────────────────────────────
// Loads available entity type schemas AND searches for relevant data.
// The synthesis step uses both to produce patterns, trends, and insights.

const analyticalProcess: Process = hydrateProcess({
    schema_version: 1,
    key: 'phaibel.analytical',
    description: 'Analyze patterns, trends, productivity levels, or insights across the user\'s stored data',
    context: {},
    nodes: [
        {
            key: 'start',
            catalog_node_key: 'start',
            configuration: {},
            edges: { ok: 'load_types' },
        },
        {
            key: 'load_types',
            description: 'Load entity type schemas to understand data structure',
            catalog_node_key: 'list_entity_types',
            configuration: {},
            edges: { ok: 'search' },
        },
        {
            key: 'search',
            description: 'Search for relevant data to analyze',
            catalog_node_key: 'search_entities',
            configuration: { context_path: 'search_results' },
            edges: { ok: 'done', not_found: 'done', error: 'done' },
        },
        {
            key: 'done',
            catalog_node_key: 'stop',
            configuration: {},
            edges: {},
        },
    ],
});

// ── introspection ─────────────────────────────────────────────────────────────
// Describes what the assistant knows and can do: lists all registered entity
// types and samples stored data for a holistic picture.

const introspectionProcess: Process = hydrateProcess({
    schema_version: 1,
    key: 'phaibel.introspection',
    description: 'Answer questions about what data is stored, what the assistant knows about the user, or what Phaibel can do',
    context: {},
    nodes: [
        {
            key: 'start',
            catalog_node_key: 'start',
            configuration: {},
            edges: { ok: 'load_types' },
        },
        {
            key: 'load_types',
            description: 'List all registered entity types so the assistant can describe available data',
            catalog_node_key: 'list_entity_types',
            configuration: {},
            edges: { ok: 'search' },
        },
        {
            key: 'search',
            description: 'Broad search to sample representative stored data',
            catalog_node_key: 'search_entities',
            configuration: { context_path: 'search_results' },
            edges: { ok: 'done', not_found: 'done', error: 'done' },
        },
        {
            key: 'done',
            catalog_node_key: 'stop',
            configuration: {},
            edges: {},
        },
    ],
});

// ── factual ───────────────────────────────────────────────────────────────────
// Runs a live web search for current real-world data: weather, exchange rates,
// news, flight status, sports scores, etc. Uses web_search node code which
// routes through Synaptic (subscription) or Perplexity direct API (BYOK).

const factualProcess: Process = hydrateProcess({
    schema_version: 1,
    key: 'phaibel.factual',
    description: 'Look up current real-world information: weather, exchange rates, stock prices, news, flight status, sports scores, or any live factual data',
    context: {},
    nodes: [
        {
            key: 'start',
            catalog_node_key: 'start',
            configuration: {},
            edges: { ok: 'search' },
        },
        {
            key: 'search',
            description: 'Search the web for current factual data',
            catalog_node_key: 'web_search',
            configuration: {
                query: '{user_input}',
                response_context_path: 'search_result',
            },
            edges: { ok: 'done', error: 'done' },
        },
        {
            key: 'done',
            catalog_node_key: 'stop',
            configuration: {},
            edges: {},
        },
    ],
});

// ─────────────────────────────────────────────────────────────────────────────
// Exports
// ─────────────────────────────────────────────────────────────────────────────

export const CATEGORY_PROCESSES: Process[] = [
    queryProcess,
    analyticalProcess,
    introspectionProcess,
    factualProcess,
];

/** Maps a RequestCategory to its pre-built process key, or undefined if none. */
export const CATEGORY_PROCESS_KEY: Partial<Record<RequestCategory, string>> = {
    query:         'phaibel.query',
    analytical:    'phaibel.analytical',
    introspection: 'phaibel.introspection',
    factual:       'phaibel.factual',
};
