// ─────────────────────────────────────────────────────────────────────────────
// Feral CCF — Life Primitives Catalog Source
//
// Intent-named action nodes for the seven built-in entity types.
// These complement the CRUD + field-setter nodes auto-generated by
// EntityCatalogSource with three kinds of semantic actions:
//
//   (a) Multi-field atomic operations — rename_person, reschedule_event
//   (b) Pre-configured state transitions — start_task, cancel_event, abandon_goal
//   (c) Typed graph edges between life primitives — link_task_to_goal, add_event_attendee
//
// Context interpolation: config values that contain {key} are resolved from
// the process context at runtime, so "source_entity_title": "{person_title}"
// means the LLM must set person_title in context before calling this node.
// ─────────────────────────────────────────────────────────────────────────────

import type { CatalogNode } from './catalog-node.js';
import type { CatalogSource } from './catalog.js';

export class LifePrimitivesCatalogSource implements CatalogSource {
    getCatalogNodes(): CatalogNode[] {
        return [
            ...personNodes(),
            ...taskNodes(),
            ...eventNodes(),
            ...goalNodes(),
            ...noteNodes(),
            ...companyNodes(),
        ];
    }
}

// ── PERSON ────────────────────────────────────────────────────────────────────

function personNodes(): CatalogNode[] {
    return [
        {
            key: 'rename_person',
            nodeCodeKey: 'update_entity',
            name: 'Rename Person',
            group: 'person',
            description: 'Renames a person — updates their first name and/or last name together. Set "title" (current name), "name" (new first name), and/or "lastName" (new last name) in context.',
            configuration: {
                entity_type: 'person',
                patch_fields: 'name,lastName',
            },
        },
        {
            key: 'link_person_to_company',
            nodeCodeKey: 'link_entities',
            name: 'Link Person to Company',
            group: 'person',
            description: 'Creates a graph edge from a person to their employer. Set "person_title" and "company_title" in context.',
            configuration: {
                source_entity_type: 'person',
                source_entity_title: '{person_title}',
                target_entity_type: 'company',
                target_entity_title: '{company_title}',
                label: 'works-at',
            },
        },
        {
            key: 'link_person_to_person',
            nodeCodeKey: 'link_entities',
            name: 'Link Person to Person',
            group: 'person',
            description: 'Creates a directed relationship between two people. Set "source_title" (FROM), "target_title" (TO), and "link_label" (e.g. "reports-to", "spouse-of", "friend-of", "manages") in context.',
            configuration: {
                source_entity_type: 'person',
                source_entity_title: '{source_title}',
                target_entity_type: 'person',
                target_entity_title: '{target_title}',
                label: '{link_label}',
            },
        },
        {
            key: 'link_person_to_goal',
            nodeCodeKey: 'link_entities',
            name: 'Link Person to Goal',
            group: 'person',
            description: 'Connects a person to a goal — for ownership or stakeholder tracking. Set "person_title", "goal_title", and "link_label" (e.g. "owner-of", "stakeholder-of", "accountable-for") in context.',
            configuration: {
                source_entity_type: 'person',
                source_entity_title: '{person_title}',
                target_entity_type: 'goal',
                target_entity_title: '{goal_title}',
                label: '{link_label}',
            },
        },
    ];
}

// ── TASK ──────────────────────────────────────────────────────────────────────

function taskNodes(): CatalogNode[] {
    return [
        {
            key: 'start_task',
            nodeCodeKey: 'set_entity_field',
            name: 'Start Task',
            group: 'task',
            description: 'Marks a task as in-progress. Set "title" to the task name in context.',
            configuration: {
                entity_type: 'task',
                field: 'status',
                value: 'in-progress',
            },
        },
        {
            key: 'block_task',
            nodeCodeKey: 'set_entity_field',
            name: 'Block Task',
            group: 'task',
            description: 'Marks a task as blocked. Set "title" to the task name in context.',
            configuration: {
                entity_type: 'task',
                field: 'status',
                value: 'blocked',
            },
        },
        {
            key: 'reopen_task',
            nodeCodeKey: 'set_entity_field',
            name: 'Reopen Task',
            group: 'task',
            description: 'Reopens a completed or blocked task, resetting status to open. Set "title" in context.',
            configuration: {
                entity_type: 'task',
                field: 'status',
                value: 'open',
            },
        },
        {
            key: 'reschedule_task',
            nodeCodeKey: 'update_entity',
            name: 'Reschedule Task',
            group: 'task',
            description: 'Moves a task to a new due date and/or start date. Set "title", "dueDate" (YYYY-MM-DD), and optionally "startDate" in context.',
            configuration: {
                entity_type: 'task',
                patch_fields: 'dueDate,startDate',
            },
        },
        {
            key: 'link_task_to_goal',
            nodeCodeKey: 'link_entities',
            name: 'Link Task to Goal',
            group: 'task',
            description: 'Marks a task as contributing to a goal. Set "task_title" and "goal_title" in context.',
            configuration: {
                source_entity_type: 'task',
                source_entity_title: '{task_title}',
                target_entity_type: 'goal',
                target_entity_title: '{goal_title}',
                label: 'contributes-to',
            },
        },
        {
            key: 'link_task_to_task',
            nodeCodeKey: 'link_entities',
            name: 'Link Task to Task (Blocks)',
            group: 'task',
            description: 'Marks one task as blocking another. Set "source_title" (the blocker) and "target_title" (the task being blocked) in context.',
            configuration: {
                source_entity_type: 'task',
                source_entity_title: '{source_title}',
                target_entity_type: 'task',
                target_entity_title: '{target_title}',
                label: 'blocks',
            },
        },
        {
            key: 'assign_task_to_person',
            nodeCodeKey: 'link_entities',
            name: 'Assign Task to Person',
            group: 'task',
            description: 'Links a task to the person responsible for it. Set "task_title" and "person_title" in context.',
            configuration: {
                source_entity_type: 'task',
                source_entity_title: '{task_title}',
                target_entity_type: 'person',
                target_entity_title: '{person_title}',
                label: 'assigned-to',
            },
        },
    ];
}

// ── EVENT ─────────────────────────────────────────────────────────────────────

function eventNodes(): CatalogNode[] {
    return [
        {
            key: 'reschedule_event',
            nodeCodeKey: 'update_entity',
            name: 'Reschedule Event',
            group: 'event',
            description: 'Moves an event to a new time and/or duration. Set "title", "startDate" (ISO datetime with timezone), and optionally "duration" (e.g. "1h", "90m") in context.',
            configuration: {
                entity_type: 'event',
                patch_fields: 'startDate,duration',
            },
        },
        {
            key: 'cancel_event',
            nodeCodeKey: 'set_entity_field',
            name: 'Cancel Event',
            group: 'event',
            description: 'Marks an event as cancelled. Set "title" to the event name in context.',
            configuration: {
                entity_type: 'event',
                field: 'status',
                value: 'cancelled',
            },
        },
        {
            key: 'confirm_event',
            nodeCodeKey: 'set_entity_field',
            name: 'Confirm Event',
            group: 'event',
            description: 'Marks a tentative event as confirmed. Set "title" to the event name in context.',
            configuration: {
                entity_type: 'event',
                field: 'status',
                value: 'confirmed',
            },
        },
        {
            key: 'add_event_attendee',
            nodeCodeKey: 'link_entities',
            name: 'Add Event Attendee',
            group: 'event',
            description: 'Links a person to an event as an attendee. Set "person_title" and "event_title" in context.',
            configuration: {
                source_entity_type: 'person',
                source_entity_title: '{person_title}',
                target_entity_type: 'event',
                target_entity_title: '{event_title}',
                label: 'attending',
            },
        },
        {
            key: 'link_event_to_goal',
            nodeCodeKey: 'link_entities',
            name: 'Link Event to Goal',
            group: 'event',
            description: 'Connects an event to the goal it advances (e.g. a planning meeting linked to a strategic goal). Set "event_title" and "goal_title" in context.',
            configuration: {
                source_entity_type: 'event',
                source_entity_title: '{event_title}',
                target_entity_type: 'goal',
                target_entity_title: '{goal_title}',
                label: 'advances',
            },
        },
    ];
}

// ── GOAL ──────────────────────────────────────────────────────────────────────

function goalNodes(): CatalogNode[] {
    return [
        {
            key: 'abandon_goal',
            nodeCodeKey: 'set_entity_field',
            name: 'Abandon Goal',
            group: 'goal',
            description: 'Marks a goal as abandoned. Set "title" to the goal name in context.',
            configuration: {
                entity_type: 'goal',
                field: 'status',
                value: 'abandoned',
            },
        },
        {
            key: 'activate_goal',
            nodeCodeKey: 'set_entity_field',
            name: 'Activate Goal',
            group: 'goal',
            description: 'Sets a goal status back to active — useful when reviving an abandoned goal. Set "title" in context.',
            configuration: {
                entity_type: 'goal',
                field: 'status',
                value: 'active',
            },
        },
        {
            key: 'link_goal_to_goal',
            nodeCodeKey: 'link_entities',
            name: 'Link Goal to Goal',
            group: 'goal',
            description: 'Creates a relationship between two goals. Set "source_title", "target_title", and "link_label" (e.g. "milestone-of", "sub-goal-of", "depends-on") in context.',
            configuration: {
                source_entity_type: 'goal',
                source_entity_title: '{source_title}',
                target_entity_type: 'goal',
                target_entity_title: '{target_title}',
                label: '{link_label}',
            },
        },
    ];
}

// ── NOTE ──────────────────────────────────────────────────────────────────────

function noteNodes(): CatalogNode[] {
    return [
        {
            key: 'rename_note',
            nodeCodeKey: 'update_entity',
            name: 'Rename Note',
            group: 'note',
            description: 'Renames a note. Set "title" (current name) and "name" (new name) in context.',
            configuration: {
                entity_type: 'note',
                patch_fields: 'name',
            },
        },
        {
            key: 'link_note_to_person',
            nodeCodeKey: 'link_entities',
            name: 'Link Note to Person',
            group: 'note',
            description: 'Attaches a note to the person it is about. Set "note_title" and "person_title" in context.',
            configuration: {
                source_entity_type: 'note',
                source_entity_title: '{note_title}',
                target_entity_type: 'person',
                target_entity_title: '{person_title}',
                label: 'about',
            },
        },
        {
            key: 'link_note_to_task',
            nodeCodeKey: 'link_entities',
            name: 'Link Note to Task',
            group: 'note',
            description: 'Links a note to a related task. Set "note_title" and "task_title" in context.',
            configuration: {
                source_entity_type: 'note',
                source_entity_title: '{note_title}',
                target_entity_type: 'task',
                target_entity_title: '{task_title}',
                label: 'related-to',
            },
        },
        {
            key: 'link_note_to_goal',
            nodeCodeKey: 'link_entities',
            name: 'Link Note to Goal',
            group: 'note',
            description: 'Links a note to the goal it supports. Set "note_title" and "goal_title" in context.',
            configuration: {
                source_entity_type: 'note',
                source_entity_title: '{note_title}',
                target_entity_type: 'goal',
                target_entity_title: '{goal_title}',
                label: 'supports',
            },
        },
        {
            key: 'link_note_to_event',
            nodeCodeKey: 'link_entities',
            name: 'Link Note to Event',
            group: 'note',
            description: 'Attaches a note to an event — e.g. meeting notes from a call. Set "note_title" and "event_title" in context.',
            configuration: {
                source_entity_type: 'note',
                source_entity_title: '{note_title}',
                target_entity_type: 'event',
                target_entity_title: '{event_title}',
                label: 'from',
            },
        },
        {
            key: 'link_note_to_company',
            nodeCodeKey: 'link_entities',
            name: 'Link Note to Company',
            group: 'note',
            description: 'Attaches a note to a company. Set "note_title" and "company_title" in context.',
            configuration: {
                source_entity_type: 'note',
                source_entity_title: '{note_title}',
                target_entity_type: 'company',
                target_entity_title: '{company_title}',
                label: 'about',
            },
        },
    ];
}

// ── COMPANY ───────────────────────────────────────────────────────────────────

function companyNodes(): CatalogNode[] {
    return [
        {
            key: 'rename_company',
            nodeCodeKey: 'update_entity',
            name: 'Rename Company',
            group: 'company',
            description: 'Renames a company. Set "title" (current name) and "name" (new name) in context.',
            configuration: {
                entity_type: 'company',
                patch_fields: 'name',
            },
        },
        {
            key: 'link_company_to_person',
            nodeCodeKey: 'link_entities',
            name: 'Set Company Primary Contact',
            group: 'company',
            description: 'Links a company to its primary contact person via a graph edge. Set "company_title" and "person_title" in context.',
            configuration: {
                source_entity_type: 'company',
                source_entity_title: '{company_title}',
                target_entity_type: 'person',
                target_entity_title: '{person_title}',
                label: 'primary-contact',
            },
        },
        {
            key: 'link_company_to_company',
            nodeCodeKey: 'link_entities',
            name: 'Link Company to Company',
            group: 'company',
            description: 'Relates two companies. Set "source_title", "target_title", and "link_label" (e.g. "subsidiary-of", "partner-of", "acquired-by", "competes-with") in context.',
            configuration: {
                source_entity_type: 'company',
                source_entity_title: '{source_title}',
                target_entity_type: 'company',
                target_entity_title: '{target_title}',
                label: '{link_label}',
            },
        },
        {
            key: 'link_company_to_goal',
            nodeCodeKey: 'link_entities',
            name: 'Link Company to Goal',
            group: 'company',
            description: 'Connects a company to a related goal (e.g. a client linked to a revenue goal). Set "company_title", "goal_title", and "link_label" (e.g. "client-for", "funds", "drives") in context.',
            configuration: {
                source_entity_type: 'company',
                source_entity_title: '{company_title}',
                target_entity_type: 'goal',
                target_entity_title: '{goal_title}',
                label: '{link_label}',
            },
        },
    ];
}
